using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using UnionSupport.Generator.Product;

namespace UnionSupport.Tests.Product;

/// <summary>
/// Behavioral tests for the generated Product union code.
/// Note: implicit operators are NOT generated by the source generator —
/// they are provided by the C# 15 compiler when it sees the [Union] attribute.
/// See generator line 92: "// AppendImplicitOps(sb, info); // removed: implicit operators not needed (C# 15 union provides them)"
/// </summary>
public sealed class BehavioralTests
{
    private static readonly CSharpParseOptions ParseOptions = CSharpParseOptions.Default
        .WithLanguageVersion(LanguageVersion.Latest);

    private static readonly string[] CoreSources =
    [
        """
        namespace UnionSupport;
        public enum UnionImplementationStrategy { Product = 0, Unmanaged = 1, ObjectErasure = 2 }
        """,
        """
        namespace UnionSupport;
        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = false)]
        public sealed class UnionImplAttribute : System.Attribute
        {
            public UnionImplementationStrategy Strategy { get; }
            public UnionImplAttribute(UnionImplementationStrategy strategy = UnionImplementationStrategy.Product) { Strategy = strategy; }
        }
        """
    ];

    private static readonly MetadataReference[] Refs;

    static BehavioralTests()
    {
        var list = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Linq.Enumerable).Assembly.Location),
        };

        var runtimeDir = System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory();
        var systemRuntime = Path.Combine(runtimeDir, "System.Runtime.dll");
        if (File.Exists(systemRuntime))
            list.Add(MetadataReference.CreateFromFile(systemRuntime));

        Refs = list.ToArray();
    }

    [Fact]
    public void HasValue_DefaultStruct_ReturnsFalse()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var def = Activator.CreateInstance(t);
        Assert.Equal(false, t.GetProperty("HasValue")!.GetValue(def));
    }

    [Fact]
    public void HasValue_AfterConstructor_ReturnsTrue()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var ctor = t.GetConstructor([typeof(int)])!;
        var union = ctor.Invoke([42]);
        Assert.Equal(true, t.GetProperty("HasValue")!.GetValue(union));
    }

    [Fact]
    public void TryGetValue_MatchesType_ReturnsTrueAndValue()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var ctor = t.GetConstructor([typeof(int)])!;
        var union = ctor.Invoke([42]);

        var args = new object[] { 0 };
        var found = t.GetMethod("TryGetValue", [typeof(int).MakeByRefType()])!.Invoke(union, args);
        Assert.Equal(true, found);
        Assert.Equal(42, args[0]);
    }

    [Fact]
    public void TryGetValue_WrongType_ReturnsFalse()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var ctor = t.GetConstructor([typeof(int)])!;
        var union = ctor.Invoke([42]);

        var args = new object[] { 0f };
        var found = t.GetMethod("TryGetValue", [typeof(float).MakeByRefType()])!.Invoke(union, args);
        Assert.Equal(false, found);
    }

    [Fact]
    public void TryGetValue_FloatValue_ReturnsCorrect()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var ctor = t.GetConstructor([typeof(float)])!;
        var union = ctor.Invoke([3.14f]);

        var args = new object[] { 0f };
        var found = t.GetMethod("TryGetValue", [typeof(float).MakeByRefType()])!.Invoke(union, args);
        Assert.Equal(true, found);
        Assert.Equal(3.14f, args[0]);
    }

    [Fact]
    public void IUnion_Value_ReturnsStoredObject()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var ctor = t.GetConstructor([typeof(int)])!;
        var union = ctor.Invoke([42]);

        var iface = t.GetInterface("System.Runtime.CompilerServices.IUnion")!;
        var valueProp = iface.GetProperty("Value")!;
        Assert.Equal(42, valueProp.GetValue(union));
    }

    [Fact]
    public void IUnion_Value_Default_ReturnsNull()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        var def = Activator.CreateInstance(t);
        var iface = t.GetInterface("System.Runtime.CompilerServices.IUnion")!;
        var valueProp = iface.GetProperty("Value")!;
        Assert.Null(valueProp.GetValue(def));
    }

    [Fact]
    public void ThreeTypes_AllConstructorsAndTryGetValueWork()
    {
        var t = CompileAndGetType("""
            using UnionSupport;
            [UnionImpl] partial struct Triple(int a, string b, double c);
            """);

        // int value
        var ctorInt = t.GetConstructor([typeof(int)])!;
        var u1 = ctorInt.Invoke([10]);
        var args1 = new object[] { 0 };
        Assert.Equal(true, t.GetMethod("TryGetValue", [typeof(int).MakeByRefType()])!.Invoke(u1, args1));
        Assert.Equal(10, args1[0]);

        // string value
        var ctorStr = t.GetConstructor([typeof(string)])!;
        var u2 = ctorStr.Invoke(["hello"]);
        var args2 = new object[] { "" };
        Assert.Equal(true, t.GetMethod("TryGetValue", [typeof(string).MakeByRefType()])!.Invoke(u2, args2));
        Assert.Equal("hello", args2[0]);

        // double value
        var ctorDbl = t.GetConstructor([typeof(double)])!;
        var u3 = ctorDbl.Invoke([3.14]);
        var args3 = new object[] { 0.0 };
        Assert.Equal(true, t.GetMethod("TryGetValue", [typeof(double).MakeByRefType()])!.Invoke(u3, args3));
        Assert.Equal(3.14, args3[0]);
    }

    [Fact]
    public void GeneratedCode_HasUnionAttribute()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.Contains("[global::System.Runtime.CompilerServices.Union]", source);
    }

    [Fact]
    public void GeneratedCode_ImplementsIUnion()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.Contains(": global::System.Runtime.CompilerServices.IUnion", source);
    }

    [Fact]
    public void GeneratedCode_HasHasValue()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.Contains("public bool HasValue", source);
    }

    [Fact]
    public void GeneratedCode_HasTryGetValue()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.Contains("public bool TryGetValue(out int value)", source);
        Assert.Contains("public bool TryGetValue(out float value)", source);
    }

    [Fact]
    public void GeneratedCode_HasConstructors()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.Contains("public MyUnion(int value)", source);
        Assert.Contains("public MyUnion(float value)", source);
    }

    [Fact]
    public void GeneratedCode_DoesNotHaveImplicitOperators()
    {
        // Implicit operators are provided by C# 15 compiler via [Union] attribute
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        Assert.DoesNotContain("implicit operator", source);
    }

    [Fact]
    public void GeneratedCode_HasGeneratedCodeAttribute()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct MyUnion(int a, float b);
            """);
        int count = source.Split("[global::System.CodeDom.Compiler.GeneratedCode(\"UnionSupport\", \"1.0.0\")]").Length - 1;
        Assert.True(count > 0);
    }

    [Fact]
    public void ZeroMembers_HasNoMembers()
    {
        var source = CompileAndGetGeneratedSource("""
            using UnionSupport;
            [UnionImpl] partial struct Empty;
            """);
        // 0 members: no fields, no HasValue, no TryGetValue, no constructors
        Assert.DoesNotContain("__private_flag", source);
        Assert.DoesNotContain("TryGetValue", source);
        Assert.DoesNotContain("HasValue", source);
        Assert.DoesNotContain("implicit operator", source);
    }

    private Type CompileAndGetType(string source)
    {
        var asm = CompileToAssembly(source);
        return asm.GetType(ExtractTypeName(source))!;
    }

    private static string CompileAndGetGeneratedSource(string source)
    {
        var trees = new List<SyntaxTree> { CSharpSyntaxTree.ParseText(source, ParseOptions) };
        trees.AddRange(CoreSources.Select(cs => CSharpSyntaxTree.ParseText(cs, ParseOptions)));

        var compilation = CSharpCompilation.Create(
            "TestAssembly", trees, Refs,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var driver = CSharpGeneratorDriver.Create(new ProductUnionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var output, out _);

        var generated = output.SyntaxTrees.Skip(trees.Count).Select(t => t.ToString()).ToList();
        return string.Join("\n", generated);
    }

    private static string ExtractTypeName(string source)
    {
        // Extract type name from "partial struct <Name>"
        var match = System.Text.RegularExpressions.Regex.Match(source, @"partial\s+struct\s+(\w+)");
        return match.Success ? match.Groups[1].Value : "Unknown";
    }

    private Assembly CompileToAssembly(string source)
    {
        var trees = new List<SyntaxTree> { CSharpSyntaxTree.ParseText(source, ParseOptions) };
        trees.AddRange(CoreSources.Select(cs => CSharpSyntaxTree.ParseText(cs, ParseOptions)));

        var compilation = CSharpCompilation.Create(
            "TestAssembly", trees, Refs,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var driver = CSharpGeneratorDriver.Create(new ProductUnionGenerator());
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var output, out _);

        using var ms = new MemoryStream();
        var result = output.Emit(ms);
        if (!result.Success)
        {
            var errors = string.Join("\n", result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
            throw new InvalidOperationException($"Compilation errors:\n{errors}");
        }

        return Assembly.Load(ms.ToArray());
    }
}
