using System.Text;

namespace UnionSupport.Generator.Shared;

internal static class UnionCodeGenerator
{
    private static string GeneratedAttr => $"[global::System.CodeDom.Compiler.GeneratedCode(\"{SourceGenHelpers.ToolName}\", \"{SourceGenHelpers.ToolVersion}\")]";

    public static string Generate(UnionTypeInfo info)
    {
        return info.StrategyName switch
        {
            "Product" => GenerateUnion(info, Fields: ProductFields, Ctors: ProductCtors, ValueExpr: ValueExpr_Flag, HasValueExpr: HasValueExpr_Flag, TryGetBody: TryGetBody_Direct),
            "Unmanaged" => GenerateUnion(info, Fields: UnmanagedFields, Ctors: UnmanagedCtors, ValueExpr: ValueExpr_Flag, HasValueExpr: HasValueExpr_Flag, TryGetBody: TryGetBody_Direct,
                extraTypeAttr: "[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]"),
            "ObjectErasure" => GenerateUnion(info, Fields: ErasureFields, Ctors: ErasureCtors, ValueExpr: ValueExpr_Erasure, HasValueExpr: HasValueExpr_Erasure, TryGetBody: TryGetBody_Erasure),
            _ => GenerateUnion(info, Fields: ProductFields, Ctors: ProductCtors, ValueExpr: ValueExpr_Flag, HasValueExpr: HasValueExpr_Flag, TryGetBody: TryGetBody_Direct)
        };
    }

    private delegate void FieldsWriter(StringBuilder sb, UnionTypeInfo info);
    private delegate void CtorsWriter(StringBuilder sb, UnionTypeInfo info);
    private delegate void ExprWriter(StringBuilder sb, UnionTypeInfo info);
    private delegate void TryGetWriter(StringBuilder sb, UnionTypeInfo info, int i);

    private static string GenerateUnion(UnionTypeInfo info,
        FieldsWriter Fields, CtorsWriter Ctors, ExprWriter ValueExpr, ExprWriter HasValueExpr, TryGetWriter TryGetBody,
        string extraTypeAttr = "")
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // primary ctor params are type declarations");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        if (info.StrategyName == "Unmanaged" && info.Members.Count > 0)
            sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        var tparams = TypeParams(info);
        var typeKw = info.IsRefStruct ? "ref struct" : (info.IsValueType ? "struct" : "class");

        if (!string.IsNullOrEmpty(extraTypeAttr))
            sb.AppendLine($"    {extraTypeAttr}");

        sb.AppendLine($"    {GeneratedAttr}");
        if (!info.IsRefStruct)
        {
            sb.AppendLine($"    [global::System.Runtime.CompilerServices.Union]");
            sb.AppendLine($"    partial {typeKw} {info.TypeName}{tparams} : global::System.Runtime.CompilerServices.IUnion");
        }
        else
        {
            sb.AppendLine($"    partial {typeKw} {info.TypeName}{tparams}");
        }
        sb.AppendLine("    {");

        if (info.Members.Count > 0)
        {
            // --- Fields ---
            Fields(sb, info);

            // --- Value property ---
            AppendValueProp(sb, info);

            // --- HasValue ---
            sb.AppendLine($"        {GeneratedAttr}");
            sb.Append("        public bool HasValue => ");
            HasValueExpr(sb, info);
            sb.AppendLine(";");
            sb.AppendLine();

            // --- TryGetValue per type ---
            for (int i = 0; i < info.Members.Count; i++)
            {
                var m = info.Members[i];
                sb.AppendLine($"        {GeneratedAttr}");
                sb.AppendLine($"        public bool TryGetValue(out {m.DisplayType} value)");
                sb.AppendLine("        {");
                TryGetBody(sb, info, i);
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // --- Constructors ---
            Ctors(sb, info);

            // --- Implicit operators ---
            AppendImplicitOps(sb, info);
        }
        else
        {
            // 0-length union still needs Value + HasValue
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine("        public object? Value => null;");
            sb.AppendLine();
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine("        public bool HasValue => false;");
            sb.AppendLine();
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        return sb.ToString();
    }

    // ═══════════════ Fields ═══════════════

    private static void ProductFields(StringBuilder sb, UnionTypeInfo info)
    {
        sb.AppendLine($"        {GeneratedAttr}");
        sb.AppendLine("        private byte __private_flag;");
        for (int i = 0; i < info.Members.Count; i++)
        {
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        private {info.Members[i].DisplayType} {info.Members[i].FieldName};");
        }
        sb.AppendLine();
    }

    private static void UnmanagedFields(StringBuilder sb, UnionTypeInfo info)
    {
        sb.AppendLine($"        {GeneratedAttr}");
        sb.AppendLine("        [FieldOffset(0)] private byte __private_flag;");
        for (int i = 0; i < info.Members.Count; i++)
        {
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        [FieldOffset(1)] private {info.Members[i].DisplayType} {info.Members[i].FieldName};");
        }
        sb.AppendLine();
    }

    private static void ErasureFields(StringBuilder sb, UnionTypeInfo info)
    {
        sb.AppendLine($"        {GeneratedAttr}");
        sb.AppendLine("        private readonly object? __value;");
        sb.AppendLine();
    }

    // ═══════════════ Value / HasValue ═══════════════

    private static void AppendValueProp(StringBuilder sb, UnionTypeInfo info)
    {
        sb.AppendLine($"        {GeneratedAttr}");
        if (info.StrategyName == "ObjectErasure")
        {
            sb.AppendLine($"        public object? Value => __value;");
        }
        else
        {
            sb.AppendLine($"        public object? Value");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            ValueExpr_Flag(sb, info);
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        sb.AppendLine();
    }

    private static void ValueExpr_Flag(StringBuilder sb, UnionTypeInfo info)
    {
        sb.AppendLine($"                return __private_flag switch");
        sb.AppendLine("                {");
        for (int i = 0; i < info.Members.Count; i++)
        {
            sb.AppendLine($"                    {i + 1} => {info.Members[i].FieldName},");
        }
        sb.AppendLine("                    _ => null,");
        sb.AppendLine("                };");
    }

    private static void ValueExpr_Erasure(StringBuilder sb, UnionTypeInfo info)
    {
        sb.Append("=> __value");
    }

    private static void HasValueExpr_Flag(StringBuilder sb, UnionTypeInfo info)
    {
        sb.Append("__private_flag != 0");
    }

    private static void HasValueExpr_Erasure(StringBuilder sb, UnionTypeInfo info)
    {
        sb.Append("__value != null");
    }

    // ═══════════════ TryGetValue bodies ═══════════════

    private static void TryGetBody_Direct(StringBuilder sb, UnionTypeInfo info, int i)
    {
        var m = info.Members[i];
        sb.AppendLine($"            if (__private_flag == {i + 1})");
        sb.AppendLine("            {");
        sb.AppendLine($"                value = {m.FieldName};");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine($"            value = default!;");
        sb.AppendLine("            return false;");
    }

    private static void TryGetBody_Erasure(StringBuilder sb, UnionTypeInfo info, int i)
    {
        var m = info.Members[i];
        sb.AppendLine($"            if (__value is {m.DisplayType} _v)");
        sb.AppendLine("            {");
        sb.AppendLine("                value = _v;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine($"            value = default!;");
        sb.AppendLine("            return false;");
    }

    // ═══════════════ Constructors ═══════════════

    private static void ProductCtors(StringBuilder sb, UnionTypeInfo info)
    {
        for (int i = 0; i < info.Members.Count; i++)
        {
            var m = info.Members[i];
            var chain = info.IsValueType ? $" : this({PrimaryCtorChain(info, i)})" : "";
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        public {info.TypeName}({m.DisplayType} value){chain}");
            sb.AppendLine("        {");
            sb.AppendLine($"            __private_flag = {i + 1};");
            for (int j = 0; j < info.Members.Count; j++)
            {
                if (j != i)
                    sb.AppendLine($"            {info.Members[j].FieldName} = default!;");
            }
            sb.AppendLine($"            {m.FieldName} = value;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private static void UnmanagedCtors(StringBuilder sb, UnionTypeInfo info)
    {
        for (int i = 0; i < info.Members.Count; i++)
        {
            var m = info.Members[i];
            var chain = info.IsValueType ? $" : this({PrimaryCtorChain(info, i)})" : "";
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        public {info.TypeName}({m.DisplayType} value){chain}");
            sb.AppendLine("        {");
            sb.AppendLine("            this = default;");
            sb.AppendLine($"            __private_flag = {i + 1};");
            sb.AppendLine($"            {m.FieldName} = value;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private static void ErasureCtors(StringBuilder sb, UnionTypeInfo info)
    {
        for (int i = 0; i < info.Members.Count; i++)
        {
            var m = info.Members[i];
            var chain = info.IsValueType ? $" : this({PrimaryCtorChain(info, i)})" : "";
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        public {info.TypeName}({m.DisplayType} value){chain}");
            sb.AppendLine("        {");
            sb.AppendLine("            __value = value;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    // ═══════════════ Implicit operators ═══════════════

    private static void AppendImplicitOps(StringBuilder sb, UnionTypeInfo info)
    {
        var tp = TypeParams(info);
        for (int i = 0; i < info.Members.Count; i++)
        {
            var m = info.Members[i];
            sb.AppendLine($"        {GeneratedAttr}");
            sb.AppendLine($"        public static implicit operator {info.TypeName}{tp}({m.DisplayType} value)");
            sb.AppendLine($"            => new {info.TypeName}{tp}(value);");
        }
        sb.AppendLine();
    }

    // ═══════════════ Helpers ═══════════════

    private static string TypeParams(UnionTypeInfo info)
        => info.IsGeneric && info.GenericParameters.Count > 0
            ? $"<{string.Join(", ", info.GenericParameters)}>"
            : "";

    private static string PrimaryCtorChain(UnionTypeInfo info, int valueIndex)
    {
        var args = new string[info.Members.Count];
        for (int i = 0; i < info.Members.Count; i++)
        {
            args[i] = i == valueIndex ? "value" : "default!";
        }
        return string.Join(", ", args);
    }
}
