<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>UnionSupport</RootNamespace>
        <PackageId>UnionSupport.Core</PackageId>
        <Description>Core types for UnionSupport: IUnion, [UnionImpl], [Union], and strategy enum.</Description>
    </PropertyGroup>

</Project>
